version: '3.3'

networks:
  my_net:
    driver: bridge

services:
  jenkins:
    image: jenkins
    container_name: jenkins
    networks: 
      - my_net

  nginx:
    build: ./nginx
    image: my-nginx
    ports:
      - "8090:80"
      - "8091:8080"
    depends_on: 
      - jenkins
    command: '/opt/nginx/run.sh jenkins 8080'
    networks:
      - my_net
